server:
    port: 9000
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGateWayForService
 cloud:
    gateway:
      routes:
      - id: AbcBank-branch
        uri: http://localhost:9001/
        predicates:
        - Path=/Branch/**
      - id: AbcBank-Customer
        uri: http://localhost:9002/
        predicates:
        - Path=/Customer/**
      - id: AppsNa_BULT_App_JWTServiceApplication
        uri: http://localhost:8081/
        predicates:
        - Path=/api/jwt/**

