data:
   exception:
          msg: Data Already Exists!!
          dmsg: Data Doesnot Exists!!

server:
    port: 8082          
    
    
spring:
    application:
           name: AppsNa_BULT_App_ProfileService
    data:
        mongodb:
             database: AppsNaBULTApp
             host: localhost
             port: 27017
eureka:
     client:
          service-url:
                   defaultZone: http://localhost:8761/eureka/          
                          
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt
    
    
jwt:
  secret: secrectkey123                              